#!/bin/bash



if [[ $OS == Windows_NT ]]; then
    echo asm2obj on Windows
    sdccrm=.make/sdccrm.exe
    sdasstm8='/c/Program Files/SDCC/bin/sdasstm8.exe'
else
    echo asm2obj on Linux
    sdccrm=sdccrm
    sdasstm8=sdasstm8
fi

lines=()
while read line; do
  lines+=("-x")
  lines+=("$line")
done < <(tr -d '\r' <exclude_reference)

"$sdccrm" "${lines[@]}" -r $@

for soubor in $@; do 
    "$sdasstm8" -plosg -ff $soubor; 
done
